# fly.toml app configuration file generated for sqd-frontend on 2025-01-27T15:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "sqd-frontend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[env]
  NODE_ENV = "production"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
