# fly.toml app configuration file generated for sqd-backend on 2025-01-27T15:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "sqd-backend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  DB_CONNECTION = "pgsql"
  CACHE_DRIVER = "file"
  SESSION_DRIVER = "file"
  QUEUE_CONNECTION = "sync"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/static/"
