[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-scripts'
]

[phases.build]
cmds = [
  'cp env.example .env',
  'echo "DEBUG: Contents of .env file:"',
  'cat .env',
  'echo "DEBUG: Checking for APP_KEY line:"',
  'grep -n "APP_KEY" .env || echo "No APP_KEY found"',
  'mkdir -p public storage/app storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views storage/logs',
  'echo "<?php use Illuminate\\Foundation\\Application; use Illuminate\\Http\\Request; define(\"LARAVEL_START\", microtime(true)); if (file_exists(\$maintenance = __DIR__.\"/../storage/framework/maintenance.php\")) { require \$maintenance; } require_once __DIR__.\"/../vendor/autoload.php\"; \$app = require_once __DIR__.\"/../bootstrap/app.php\"; \$kernel = \$app->make(Illuminate\\Contracts\\Http\\Kernel::class); \$response = \$kernel->handle(\$request = Illuminate\\Http\\Request::capture()); \$response->send(); \$kernel->terminate(\$request, \$response);" > public/index.php',
  'chmod -R 775 storage bootstrap/cache public',
  'php artisan config:clear',
  'php artisan key:generate --force --no-interaction',
  'echo "DEBUG: Testing database connection..."',
  'php artisan tinker --execute="DB::connection()->getPdo(); echo \"Database connection successful\\n\";" || echo "Database connection failed"',
  'echo "DEBUG: Checking environment variables..."',
  'env | grep -E "^(DB_|DATABASE_)" | sort',
  'echo "DEBUG: Checking if tables exist..."',
  'php artisan tinker --execute="try { DB::table(\"migrations\")->count(); echo \"Migrations table exists\\n\"; } catch (Exception \$e) { echo \"Migrations table does not exist\\n\"; }"',
  'echo "DEBUG: Checking migration status..."',
  'php artisan migrate:status --no-interaction || echo "Could not get migration status"',
  'echo "DEBUG: Creating database tables manually via SQL to avoid PostgreSQL transaction issues..."',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE TABLE IF NOT EXISTS migrations (id SERIAL PRIMARY KEY, migration VARCHAR(255) NOT NULL, batch INTEGER NOT NULL)\\\"); echo \\\"Migrations table created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Migrations table error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Migrations table creation failed"',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, email_verified_at TIMESTAMP NULL, password VARCHAR(255) NOT NULL, remember_token VARCHAR(100) NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL)\\\"); echo \\\"Users table created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Users table error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Users table creation failed"',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE TABLE IF NOT EXISTS password_reset_tokens (email VARCHAR(255) PRIMARY KEY, token VARCHAR(255) NOT NULL, created_at TIMESTAMP NULL)\\\"); echo \\\"Password reset tokens table created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Password reset tokens table error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Password reset tokens table creation failed"',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE TABLE IF NOT EXISTS sessions (id VARCHAR(255) PRIMARY KEY, user_id BIGINT NULL, ip_address VARCHAR(45) NULL, user_agent TEXT NULL, payload TEXT NOT NULL, last_activity INTEGER NOT NULL)\\\"); echo \\\"Sessions table created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Sessions table error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Sessions table creation failed"',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE INDEX IF NOT EXISTS sessions_user_id_index ON sessions (user_id)\\\"); echo \\\"Sessions user_id index created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Sessions index error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Sessions index creation failed"',
  'php artisan tinker --execute="try { DB::statement(\\\"CREATE INDEX IF NOT EXISTS sessions_last_activity_index ON sessions (last_activity)\\\"); echo \\\"Sessions last_activity index created\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Sessions index error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Sessions index creation failed"',
  'echo "DEBUG: Marking base migration as completed..."',
  'php artisan tinker --execute="try { DB::table(\\\"migrations\\\")->insertOrIgnore([\\\"migration\\\" => \\\"0001_01_01_000000_create_users_table\\\", \\\"batch\\\" => 1]); echo \\\"Base migration marked as completed\\\\n\\\"; } catch (Exception \\$e) { echo \\\"Migration marking error: \\\" . \\$e->getMessage() . \\\"\\\\n\\\"; }" 2>&1 || echo "Migration marking failed"',
  'echo "DEBUG: Running other migrations (skipping base tables)..."',
  'SKIP_BASE_TABLES_MIGRATION=true php artisan migrate --force --no-interaction -v 2>&1 || echo "Other migrations failed but continuing..."',
  'echo "DEBUG: Running seeders..."',
  'php artisan db:seed --force --no-interaction 2>&1 || echo "Seeding failed but continuing..."',
  'php artisan config:cache --no-interaction',
  'php artisan route:cache --no-interaction'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

