[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-scripts'
]

[phases.build]
cmds = [
  'cp env.example .env',
  'echo "DEBUG: Contents of .env file:"',
  'cat .env',
  'echo "DEBUG: Checking for APP_KEY line:"',
  'grep -n "APP_KEY" .env || echo "No APP_KEY found"',
  'mkdir -p public storage/app storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views storage/logs',
  'echo "<?php use Illuminate\\Foundation\\Application; use Illuminate\\Http\\Request; define(\"LARAVEL_START\", microtime(true)); if (file_exists(\$maintenance = __DIR__.\"/../storage/framework/maintenance.php\")) { require \$maintenance; } require_once __DIR__.\"/../vendor/autoload.php\"; \$app = require_once __DIR__.\"/../bootstrap/app.php\"; \$kernel = \$app->make(Illuminate\\Contracts\\Http\\Kernel::class); \$response = \$kernel->handle(\$request = Illuminate\\Http\\Request::capture()); \$response->send(); \$kernel->terminate(\$request, \$response);" > public/index.php',
  'chmod -R 775 storage bootstrap/cache public',
  'chmod +x deploy.sh debug-railway.sh',
  'php artisan config:clear',
  'php artisan key:generate --force --no-interaction',
  'echo "DEBUG: Skipping migrations during build to avoid PostgreSQL issues..."',
  'echo "DEBUG: Migrations will be run fresh after deployment starts..."',
  'php artisan config:cache --no-interaction',
  'php artisan route:cache --no-interaction'
]

[start]
cmd = 'chmod +x deploy.sh && ./deploy.sh'

