[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-scripts'
]

[phases.build]
cmds = [
  'cp env.example .env',
  'mkdir -p public storage/app storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views storage/logs',
  'echo "<?php use Illuminate\\Foundation\\Application; use Illuminate\\Http\\Request; define(\"LARAVEL_START\", microtime(true)); if (file_exists(\$maintenance = __DIR__.\"/../storage/framework/maintenance.php\")) { require \$maintenance; } require_once __DIR__.\"/../vendor/autoload.php\"; \$app = require_once __DIR__.\"/../bootstrap/app.php\"; \$kernel = \$app->make(Illuminate\\Contracts\\Http\\Kernel::class); \$response = \$kernel->handle(\$request = Illuminate\\Http\\Request::capture()); \$response->send(); \$kernel->terminate(\$request, \$response);" > public/index.php',
  'chmod -R 775 storage bootstrap/cache public',
  'php artisan key:generate --force',
  'php artisan migrate --force',
  'php artisan config:cache',
  'php artisan route:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
